kind: Pod
apiVersion: v1
metadata:
  name: testpod
  labels:
    pod-type: communication-pod  # Added label
spec:
  containers:
    - name: c00
      image: nginx
      ports:
       - containerPort: 80
