kind: Pod
apiVersion: v1
metadata:
  name: testpod2
  labels:
    pod-type: communication-pod  # Added label
spec:
  containers:
    - name: c01
      image: httpd
      ports:
       - containerPort: 80
