apiVersion: v1
kind: Service
metadata:
  name: communication-service
spec:
  selector:
    # Label selectors to match the pods
    pod-type: communication-pod
  clusterIP: None  # Headless service, no cluster IP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
